application: hdcpgen
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /keys/.*
  script: appengine.application

- url: /(index\.html)?
  static_files: appengine_index.html
  upload: appengine_index.html
